name 'x_prometheus'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures x_prometheus'
long_description 'Installs/Configures x_prometheus'
version '0.1.0'
depends 'golang', '~> 1.7.0'
depends 'prometheus', '~> 0.5.1'
